name: Aula de GCS (PUC CAMPINAS)

run-name: ${{ github.actor }} Projeto de GCS

on: [push]
 
jobs:
  primeiro:
    name: Teste_ambiente
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event_name }} foi disparado"
      - run: echo " No ${{runner.os}}"
      - run: echo " Repositorio ${{github.repository}} na branch ${{github.ref}}"
      - run: timedatectl
      - run: ls -la       


      - name: Checkout o repositorio
        uses: actions/checkout@v4
      
      - name: Mostrar rodadndo
        run: echo  "teste"
      - name: Mostrar rodadndo
        run: echo "${{ github.event_name }} foi disparado"
      - name: listando conteudo
        run: ls -la ${{ github.workspace }}

 
  web-deploy:
    needs: Teste_ambiente
    name: 🎉 Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
 
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
    
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.user }}
          password: ${{ secrets.password }}
          server-dir: applications/teste1/
